#!/bin/bash

# Last update by pavroo August 29, 2024

LANGUAGE=${LANG:0:2}
#LANGUAGE5=${LANG:0:5}
#EL=`echo $LANGUAGE | grep el`
EN=`echo $LANGUAGE | grep en`
ES=`echo $LANGUAGE | grep es`
ESAR=`echo $LANGUAGE5 | grep es_AR`
#ESES=`echo $LANGUAGE5 | grep es_ES`
FI=`echo $LANGUAGE | grep fi`
HU=`echo $LANGUAGE | grep hu`
#IT=`echo $LANGUAGE | grep it`
PL=`echo $LANGUAGE | grep pl`
RU=`echo $LANGUAGE | grep ru`
UK=`echo $LANGUAGE | grep uk`

if [ "$ES" != "" ]; then
	if [ "$ESAR" != "" ]; then
	LANGUAGE="es_AR"
#	else
#		LANGUAGE="es_ES"
	fi
elif [ "$FI" != "" ]; then
	LANGUAGE="fi"
elif [ "$HU" != "" ]; then
	LANGUAGE="hu"
#elif [ "$IT" != "" ]; then
#	LANGUAGE="it"
elif [ "$PL" != "" ]; then
	LANGUAGE="pl"
elif [ "$RU" != "" ]; then
	LANGUAGE="ru"
elif [ "$UK" != "" ]; then
	LANGUAGE="uk"
else
	LANGUAGE="en"
fi

POS="--center --width 800 --height 480"
HTML="--html --browser"
# index page
yad --window-icon=/usr/share/pixmaps/sparky-usb-imager.png $POS $HTML --uri="index.html" --user-agent="$LANGUAGE" --uri-handler="./handler"

exit 0
